title: "Just the Docs Demo"
description: "Pure Just the Docs layout example"
theme: just-the-docs

just_the_docs:
  color_scheme: light
  search: true
  back_to_top: true
  heading_anchors: true

markdown: kramdown
highlighter: rouge 